---
- hosts: webservers
  user: ansible
  become: true
  connection: ssh
  tasks:
    - name: "installing git package"
      action: yum pkg=git state=present
      when: "'git' not in ansible_facts.packages"
      